LangString addOrReinstall ${LANG_THAI} "เพิ่ม/ติดตั้งส่วนประกอบใหม่"
LangString alreadyInstalled ${LANG_THAI} "ติดตั้งไว้แล้ว"
LangString alreadyInstalledLong ${LANG_THAI} "${PRODUCTNAME} ${VERSION} ติดตั้งอยู่แล้ว เลือกสิ่งที่ต้องการทำแล้วกด ถัดไป"
LangString appRunning ${LANG_THAI} "{{product_name}} กำลังเปิดอยู่! กรุณาปิดโปรแกรมก่อนแล้วลองอีกครั้ง"
LangString appRunningOkKill ${LANG_THAI} "{{product_name}} กำลังเปิดอยู่!$\nกด OK เพื่อปิดโปรแกรม"
LangString chooseMaintenanceOption ${LANG_THAI} "เลือกสิ่งที่ต้องการทำ"
LangString choowHowToInstall ${LANG_THAI} "เลือกวิธีติดตั้ง ${PRODUCTNAME}"
LangString createDesktop ${LANG_THAI} "สร้างทางลัดบนเดสก์ท็อป"
LangString dontUninstall ${LANG_THAI} "ไม่ถอนการติดตั้ง"
LangString dontUninstallDowngrade ${LANG_THAI} "ไม่ถอนการติดตั้ง (ตัวติดตั้งนี้ไม่อนุญาตให้ลดเวอร์ชันโดยไม่ถอนการติดตั้งก่อน)"
LangString failedToKillApp ${LANG_THAI} "ปิด {{product_name}} ไม่สำเร็จ กรุณาปิดโปรแกรมเองแล้วลองอีกครั้ง"
LangString installingWebview2 ${LANG_THAI} "กำลังติดตั้ง WebView2..."
LangString newerVersionInstalled ${LANG_THAI} "มี ${PRODUCTNAME} เวอร์ชันที่ใหม่กว่าติดตั้งอยู่แล้ว! ไม่แนะนำให้ติดตั้งเวอร์ชันเก่ากว่าทับ ถ้าต้องการจริงๆ ควรถอนการติดตั้งเวอร์ชันปัจจุบันก่อน เลือกสิ่งที่ต้องการทำแล้วกด ถัดไป"
LangString older ${LANG_THAI} "เก่ากว่า"
LangString olderOrUnknownVersionInstalled ${LANG_THAI} "มี ${PRODUCTNAME} เวอร์ชัน$R4ติดตั้งอยู่ในเครื่อง แนะนำให้ถอนการติดตั้งเวอร์ชันนั้นก่อน เลือกสิ่งที่ต้องการทำแล้วกด ถัดไป"
LangString silentDowngrades ${LANG_THAI} "ตัวติดตั้งนี้ไม่อนุญาตให้ลดเวอร์ชัน ติดตั้งแบบเงียบต่อไม่ได้ กรุณาใช้ตัวติดตั้งแบบหน้าต่างแทน$\n"
LangString unableToUninstall ${LANG_THAI} "ถอนการติดตั้งไม่สำเร็จ!"
LangString uninstallApp ${LANG_THAI} "ถอนการติดตั้ง ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_THAI} "ถอนการติดตั้งก่อนติดตั้ง"
LangString unknown ${LANG_THAI} "ที่ไม่ทราบ"
LangString webview2AbortError ${LANG_THAI} "ติดตั้ง WebView2 ไม่สำเร็จ! แอปทำงานไม่ได้ถ้าไม่มี WebView2 ลองเปิดตัวติดตั้งใหม่อีกครั้ง"
LangString webview2DownloadError ${LANG_THAI} "ผิดพลาด: ดาวน์โหลด WebView2 ไม่สำเร็จ - $0"
LangString webview2DownloadSuccess ${LANG_THAI} "ดาวน์โหลดตัวติดตั้ง WebView2 สำเร็จ"
LangString webview2Downloading ${LANG_THAI} "กำลังดาวน์โหลดตัวติดตั้ง WebView2..."
LangString webview2InstallError ${LANG_THAI} "ผิดพลาด: ติดตั้ง WebView2 ไม่สำเร็จ (รหัส $1)"
LangString webview2InstallSuccess ${LANG_THAI} "ติดตั้ง WebView2 สำเร็จ"
LangString deleteAppData ${LANG_THAI} "ลบข้อมูลของแอป (ความคืบหน้าที่บันทึกไว้)"
